name: madrasty
description: "مدارس شعلة النور - تطبيق إدارة المدارس"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.4
  http: ^1.2.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#003688"
  adaptive_icon_foreground: "assets/icons/logo_trans.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/